name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          npm ci --force

      - name: Lint (Backend)
        continue-on-error: true
        run: npm run lint:be

      - name: Test (Backend)
        run: npm run test:be

      - name: Lint and Typecheck (Frontend)
        run: |
          npm run lint:fe
          npm run typecheck

      - name: Test (Frontend)
        run: npm run test:fe
